# Generated by Django 3.2.8 on 2021-10-30 23:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypost', '0003_newpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mypost',
            new_name='Thispost',
        ),
    ]
